### ISSUE TITLE
Fix two broken/uncompilable frontend unit test files

### ISSUE THREAD

**Issue by ramjawade** [ramjawade/my-farm#86]
## Overview
Found while working #56 (HttpService). `ng test home` currently fails to even bundle/compile for two unrelated, pre-existing reasons — neither caused by #56's changes (verified against `origin/main` before that work started).

## Requirements
- **`core/weather/weather.service.spec.ts`** — `TS2339: Property 'openWeatherMap' does not exist on type '{}'.` at the `spyOnProperty(API_CONFIG.openWeatherMap, 'apiKey', 'get')` line. `API_CONFIG` was emptied to `{}` when the OpenWeather key moved server-side (#42), but this spec (and its whole "live API" stubbing setup) was never updated — `weather.service.ts` no longer reads any API key at all. This spec file needs rewriting against the current `WeatherService` (which always calls the backend `/weather` endpoint), not just a one-line fix.
- **`core/services/environment.service.spec.ts`** — all 4 tests fail with `NG0908: In this configuration Angular requires Zone.js`, introduced when `EnvironmentService` was added in #58/PR #84. Needs `provideZonelessChangeDetection()` (or equivalent) in its `TestBed.configureTestingModule`, matching the rest of the suite.

## Implementation Notes
- Confirm both failures reproduce on `main` before touching anything (they do, as of commit `98e2b1b`/`50df061`).
- These block `ng test home` from running *any* test in the project (the first is a compile error, so nothing after it bundles) — worth prioritizing.

## Acceptance Criteria
- [ ] `weather.service.spec.ts` compiles and its tests reflect the current server-side-weather implementation
- [ ] `environment.service.spec.ts`'s 4 tests pass
- [ ] `npm run test` (home project) runs to completion with no new failures
- [ ] Code reviewed, merged to main

## Status
⏳ Todo (awaiting approval)
